
Warning: require(/Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/openapi-create.php on line 2

Call Stack:
    0.0008     357240   1. {main}() /Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/openapi-create.php:0


Fatal error: require(): Failed opening required '/Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/../vendor/autoload.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/openapi-create.php on line 2

Call Stack:
    0.0008     357240   1. {main}() /Users/niek/Documents/Yard/PHP/plugin-openwoo/docs/openapi-create.php:0

